---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  prepare:
    url: "https://raw.githubusercontent.com/moneyadviceservice/mas-standards/master/.rubocop.yml"
    path: ".rubocop.yml"
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- features/
- node_modules/
- spec/
- vendor/
