- old_path: '/en/articles/employers'
  new_path: 'https://www.moneyandpensionsservice.org.uk/financial-wellbeing-in-the-workplace/'
- old_path: '/en/uk_strategies/uk-strategy'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/calls-to-action'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/working-age'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/workplace-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/workplace-steering-group-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/young-adults'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/young-adults-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/savings-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/savings-steering-group-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/people-trying-save'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/children-and-young-people'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/children-young-people-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/children-young-people-steering-group-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/people-financial-difficulties'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/debt-advice-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/people-financial-difficulties-steering-group-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/retirement-planning'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/retirement-planning-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/people-planning-retire-steering-group-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/lifestages/people-retirement'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/people-retirement-steering-group'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/people-retirement-steering-group-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/regional_strategies/scotland'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/scotland-forum'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/scotland-forum-updates'
  new_path: 'https://www.moneyandpensggionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/regional_strategies/wales'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/wales-forum'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/wales-forum-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/regional_strategies/northern-ireland'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/northern-ireland-forum'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/articles/northern-ireland-forum-updates'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: '/en/regional_strategies/strategaeth-galluogrwydd-ariannol-cymru'
  new_path: 'https://www.moneyandpensionsservice.org.uk/cy/strategaeth-y-du-ar-gyfer-llesiant-ariannol-2/'
- old_path: '/en/articles/cymru-fforwm'
  new_path: 'https://www.moneyandpensionsservice.org.uk/cy/strategaeth-y-du-ar-gyfer-llesiant-ariannol-2/'
- old_path: '/en/articles/diweddariadau-fforwm-cymru'
  new_path: 'https://www.moneyandpensionsservice.org.uk/cy/strategaeth-y-du-ar-gyfer-llesiant-ariannol-2/'
- old_path: '/en/talkmoneyweek'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/talk-money-week-2018'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/talk-money-week'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/talkmoneymap'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/fincap-week-2017-events'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/fincap-week-2017-in-scotland'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/fincap-week-in-wales'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/fincap-week-is-changing'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/news/financial-capability-week-2016'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/en/articles/talk-money17-keynotes'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/talk-money-talk-pensions-week-2019/talk-money-talk-pensions-week-get-involved/'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/talk-money-talk-pensions-week-2019/'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/talk-money-talk-pensions-week-2019/talk-money-talk-pensions-week/'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: '/fincap-week'
  new_path: 'https://www.moneyandpensionsservice.org.uk/talk-money-week/'
- old_path: 'https://masassets.blob.core.windows.net/fincap-cms/files/000/000/094/original/Young_Adults_Action_Plan.pdf'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
- old_path: 'https://masassets.blob.core.windows.net/fincap-cms/files/000/000/093/original/Children___Young_People_Action_Plan.pdf'
  new_path: 'https://www.moneyandpensionsservice.org.uk/uk-strategy-for-financial-wellbeing/'
