#!/bin/bash -l

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
    bundle config github.com $GITHUB_USER:$GITHUB_PASS
    mv config/database{-jenkins,}.yml
fi

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build

exit_code=0

function run {
    declare -a tests_command=("$@")
    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run npm install -quiet
run bundle install --quiet
run bundle exec bowndler install -allow-root
run bundle exec rake db:setup
run bundle exec rubocop .
run bundle exec cucumber -f progress
run bundle exec rspec -f progress
run ./node_modules/karma/bin/karma start spec/javascripts/karma.conf.js
run brakeman -q --no-pager --ensure-latest
run bundle exec danger --verbose

exit "$exit_code"
